apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: web
  labels: { app: webapp }
spec:
  replicas: 2
  selector: { matchLabels: { app: webapp } }
  template:
    metadata: { labels: { app: webapp } }
    spec:
      containers:
        - name: webapp
          image: chand1950/flask-config-api:v3
          ports: [{ containerPort: 8080 }]
